# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
     paths:
       [ learn-git/.github/workflows/azure.yml ]
    


env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use
  PROJECT_SPN: 'NULL'  

jobs:
  azure-access:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
      # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: {{ secrets.AZURE_CREDENTIALS }} 
    
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        with:
      # Specify the script here
          inlineScript:  |
            acc_spn=$(az account show)
            ::set-env PROJECT_SPN=PROJECT_SPN::$acc_spn
      

      - uses: actions/checkout@v2
      - name: Test gh secrets action
        uses: ./
        with:
          repository: kornicameister/gh-secrets-action
          token: ${{ secrets.ACTION_PAT }}
          secrets: |
            AZURE_CRED1: {{ env.PROJECT_SPN }}

    
   
 
