
name: Create project secret for azure access
on:
  push:
     paths:
       [ .github/workflows/azure.yaml ]
    
jobs:
  azure-access:
    env:
      PROJECT_SPN: 'NULL'  
    runs-on: ubuntu-latest
    
    steps:
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI Action
        uses: azure/CLI@v1
        with:
      # Specify the script here
          inlineScript:  |
            acc_spn=$(az account show)
            echo  "::set-env name=PROJECT_SPN::$acc_spn"
      

      - uses: Nochisoft/gh-secrets-action@master
      - name: Test gh secrets action
        uses: ./
        with:
          token: ${{ secrets.ACTION_PAT }}
          secrets: |
            AZURE_CRED1: {{ env.PROJECT_SPN }}

    
   
 
